### ISSUE TITLE
Spanning Tree selectNewParent logic doesn't match the parent selection logic in Update

### ISSUE THREAD

**Issue by devonh** [matrix-org/pinecone#9]
The current `selectNewParent` logic doesn't always grab the best parent. The parent it does select depends on the order of peers stored in the switch. 
(ie. If Peer B at switch[2] has fewer hops than Peer A at switch[1] then Peer B will be selected as parent even if it has a weaker root key than Peer A, just because Peer B is connected later in the switch)
https://github.com/matrix-org/pinecone/blob/74f885644c1bf45e02ca3031a3acc58544986616/router/tree.go#L129-L140

This doesn't really matter because the node will eventually converge on using it's best parent due to the `Update` logic called when receiving tree announcements from peers. The only downside being more intermediary parents may be selected before converging on the best parent.
From this I gather the best parent should be the peer with the best root key and shortest number of hops to that root:
https://github.com/matrix-org/pinecone/blob/74f885644c1bf45e02ca3031a3acc58544986616/router/tree.go#L319-L340

Should the `selectNewParent` logic be updated to match the `Update` logic?

Such as:
``` go
var newBest = false
if ann.RootPublicKey.CompareTo(bestKey) > 0 {
	newBest = true
} else if ann.RootPublicKey.CompareTo(bestKey) == 0 && hops < bestDist {
	newBest = true
}

if newBest {
	bestKey = ann.RootPublicKey
	bestDist = hops
	bestPort = p.port
	bestTime = ann.at
	bestAnn = ann
}
```

**Comment by Arceliar** [comment]
@neilalexander FYI I tested a slight variation on this:

``` go
 switch {
 case ann.RootPublicKey.CompareTo(bestKey) < 0:
 case hops > bestDist:
 case !ann.at.Before(bestTime):
 default:
         bestKey = ann.RootPublicKey
         bestDist = hops
         bestPort = p.port
         bestTime = ann.at
         bestAnn = ann
 }
```

It seems to improve things a little in the [meshnet-lab](https://github.com/mwarning/meshnet-lab/) mobility tests. It's still not as good as I'd expect to see (c.f. Yggdrasil), but very roughly speaking:
1. `mobility1` looks *much* better. I didn't run through the full set of tests, since that takes a while, but the 10m steps every 10s previously started at around 80% and only got worse from there. Now it seems to be staying at 100%.
2. `mobility2` is still pretty rough, in that it crashes to around 0%. However, it takes longer to get to 0, and there are more points in the test where it starts to recover some performance (and it seems to recover more when this happens -- around 5-7% working routes instead of 1-2%).
3. Most interesting, none of the tests (so far) have had a group of nodes get stuck at 100% CPU. That tended to happen a lot on my machine with the mobility tests, particularly `mobility2`.

**Comment by neilalexander** [comment]
This is an excellent catch, thank you @devonh for digging deep enough to pick up on it.

I've pushed a commit that updates the `selectNewParent` logic as per @Arceliar's suggestion. I'll run some more tests with `meshnet-lab`.

**Comment by devonh** [comment]
> This is an excellent catch, thank you @devonh for digging deep enough to pick up on it.
> 
> I've pushed a commit that updates the `selectNewParent` logic as per @Arceliar's suggestion. I'll run some more tests with `meshnet-lab`.

Happy to help!

**Comment by devonh** [comment]
I looked through the new logic and it is an improvement but it still doesn't seem to align with what is happening in the `Update` function.
With the way the switch statement is structured now, it only replaces the best parent if they are better than or equal to the previous best in **every** category (with the timestamp being only better than).
ie. the new logic is:
If the root key is better or equal, **and** the hop distance is shorter or equal, **and** the last announcement is older, replace the best peer with this one.

While this won't lead to selecting arbitrary parents like before, it is much more picky than it needs to be.
ie. If the next peer has a better root key but a longer hop distance, in the new logic it would be skipped over. Shouldn't any peer with a stronger root key (that still has a valid announcement timestamp) be better regardless of the hop length or announcement age?

I believe the logic should match the `Update` logic with the addition of the announcement age as an additional tiebreaker.
ie:
If the root key is stronger, replace the best peer with this one.
else... If the root key is the same but the hop distance is shorter, replace the best peer with this one.
else... If the root key and hop distance are the same but the last announcement is older, replace the best peer with this one.
else... skip over this peer as it isn't a better parent candidate.

**Comment by devonh** [comment]
Also - now that I think about it, the `Update` logic will always replace the parent if an announcement comes in from a parent with a shorter hop distance.
Maybe that also needs changing somehow to account for announcement age (ie. we want to keep the parent with the least latency connection up to the root, not necessarily the one with the shortest hop distance.)
Would need a way of testing this using simulated peer connection latency to see if it actually makes a difference.

**Comment by neilalexander** [comment]
> With the way the switch statement is structured now, it only replaces the best parent if they are better than or equal to the previous best in every category (with the timestamp being only better than).

Just double-checked and I think this isn't true and I've updated that snippet of code to hopefully better reflect what's going on (as it may not be clear that Go `switch` blocks don't automatically fall through):

https://github.com/matrix-org/pinecone/blob/3d1f045de93bac238c82b9d9a6dedec10574144f/router/tree.go#L129-L147

> Also - now that I think about it, the Update logic will always replace the parent if an announcement comes in from a parent with a shorter hop distance.
> Maybe that also needs changing somehow to account for announcement age (ie. we want to keep the parent with the least latency connection up to the root, not necessarily the one with the shortest hop distance.)

I think the relevant factor here is that `selectNewParent` has to care about the announcement age explicitly (which is the `.at` field in the root announcement struct) because it can be called in response to non-announcement-related conditions (usually a switch peer dropping). We use that as an additional tie break so that, all else equal, we'll pick the peering that gave us the announcement first (which should correlate to the lowest latency to the root).

On the other hand, `Update` is called in direct response to a root announcements coming in from each peer, so by that logic, it should be called for the peer with the lowest latency path to the root first and other peers afterwards. Therefore, the latency is pretty much already dealt with implicitly by being called first for a given peer, and a later announcement from a slower peer would have to be stronger in other ways (shorter path, stronger key, etc) to win.

**Comment by devonh** [comment]
> > With the way the switch statement is structured now, it only replaces the best parent if they are better than or equal to the previous best in every category (with the timestamp being only better than).
> 
> Just double-checked and I think this isn't true and I've updated that snippet of code to hopefully better reflect what's going on (as it may not be clear that Go `switch` blocks don't automatically fall through):
> 
> https://github.com/matrix-org/pinecone/blob/3d1f045de93bac238c82b9d9a6dedec10574144f/router/tree.go#L129-L147
> 
That was how I first read it as well. But it only holds true for certain orderings of peers on the switch.
Say you have 2 peers. A has root key FFDD, and hop distance 2, B has root key FFFF and hop distance 4.
The parent selection logic would select A currently (since it is first in the switch) and not select B because B has a longer hop distance than A therefore entering into the second case of the switch, even though B has a better root key than A. The same logic could be applied to the announcement age.

> > Also - now that I think about it, the Update logic will always replace the parent if an announcement comes in from a parent with a shorter hop distance.
> > Maybe that also needs changing somehow to account for announcement age (ie. we want to keep the parent with the least latency connection up to the root, not necessarily the one with the shortest hop distance.)
> 
> I think the relevant factor here is that `selectNewParent` has to care about the announcement age explicitly (which is the `.at` field in the root announcement struct) because it can be called in response to non-announcement-related conditions (usually a switch peer dropping). We use that as an additional tie break so that, all else equal, we'll pick the peering that gave us the announcement first (which should correlate to the lowest latency to the root).
> 

That makes sense. My comment was under the assumption that the announcement time might be a more important factor than the hop distance when selecting a new parent. If the hop distance remains a more important factor, then the `Update` and parent selction logic match.

**Comment by neilalexander** [comment]
> That was how I first read it as well. But it only holds true for certain orderings of peers on the switch.

I've hopefully fixed this now in ad88309d26deef733013b1e337f232af06bc76ab.

**Comment by devonh** [comment]
Yeah, I think that's a lot better. I believe this line should be changed from:
https://github.com/matrix-org/pinecone/blob/21e3b392289b9412aa0d290f9f03fe9a1f8909e9/router/tree.go#L147

to:
``` go
 return ann.RootPublicKey.CompareTo(bestKey) == 0 && hops < bestDist 
 ```
 
 But otherwise the logic checks out.
 
 Until I just thought of another edge case. 
The announcement age tiebreaker only makes sense if you are comparing announcements from the same sequence. 
 ie. Peer A and Peer B both have the same root key, and the same hop distance to the root. Both peers have been receiving root announcements regularly. Our node now has to select a new parent for some reason. If we have just received the latest root announcement from Peer B but not Peer A yet, Peer A will have the older announcement age but Peer B actually has the lower latency connection up to the root.

Because of that I think the sequence number has to come into play here for a tiebreaker before the announcement age.
ie. a fourth case would need to be added, so the last case with the announcement time would be expanded into the following 2 cases:
``` go
checkWithCondition(func(ann *rootAnnouncementWithTime, hops int) bool {
		return ann.RootPublicKey.CompareTo(bestKey) == 0 && hops == bestDist && ann.Sequence > bestAnn.Sequence
	})
checkWithCondition(func(ann *rootAnnouncementWithTime, hops int) bool {
		return ann.RootPublicKey.CompareTo(bestKey) == 0 && hops == bestDist && ann.Sequence == bestAnn.Sequence && ann.at.Before(bestTime)
	})
```
 
 Any reason not to do something like this to avoid the extra map, and 3 (possibly now 4) separate map iterations?
 I also find it a lot simpler to reason about :)
 ``` go
 for _, p := range t.r.activePorts() {
    ann := p.lastAnnouncement()
    if ann == nil {
        continue
    }
    hops := len(ann.Signatures)

    var updateBest = false
    if ann.RootPublicKey.CompareTo(bestKey) < 0 {
        // The root key is stronger than our best so update our best parent.
        updateBest = true
    } else if ann.RootPublicKey.CompareTo(bestKey) == 0 && hops < bestDist {
        // The root key is the same as our best, 
        // but the hop distance is shorter so update our best parent.
        updateBest = true
    } else if ann.RootPublicKey.CompareTo(bestKey) == 0 && hops == bestDist && 
          ann.Sequence > bestAnn.Sequence {
        // The root key and hop distance are the same as our best, 
        // but this peer has received the next root announcement in the sequence,
        // implying it has lower latency between it and the root, so update our best parent.
        updateBest = true
    } else if ann.RootPublicKey.CompareTo(bestKey) == 0 && hops == bestDist && 
          ann.Sequence == bestAnn.Sequence && ann.at.Before(bestTime) {
        // The root key and hop distance are the same as our best, 
        // but this peer received the latest root announcement before our current best,
        // implying it has lower latency between it and the root, so update our best parent.
        updateBest = true
    }

    if updateBest {
        bestKey = ann.RootPublicKey
        bestDist = hops
        bestPort = p.port
        bestTime = ann.at
        bestAnn = ann
    }
}
 ```

**Comment by neilalexander** [comment]
> Yeah, I think that's a lot better. I believe this line should be changed from:

You're right, that's a bug introduced by copy-pasta. I'll push a fix for that.

> The announcement age tiebreaker only makes sense if you are comparing announcements from the same sequence.

Yes, this is a good point that has been missed out in the selection altogether here.

> Any reason not to do something like this to avoid the extra map, and 3 (possibly now 4) separate map iterations?

That's basically exactly what the `switch` statement did, but I think that's in part where the sensitivity of switch port ordering came from — I'm not 100% convinced that problem is eliminated unless we iterate more than once but I'd need to sit and think more about that to be sure.

**Comment by devonh** [comment]
> That's basically exactly what the `switch` statement did, but I think that's in part where the sensitivity of switch port ordering came from — I'm not 100% convinced that problem is eliminated unless we iterate more than once but I'd need to sit and think more about that to be sure.

Fair enough. I tried to think that through myself and I think it holds up. But it definitely starts getting harder to reason about the more peers you add into the switch.

**Comment by devonh** [comment]
The new logic looks good. I like that you check the sequence number before the hop distance. 
That makes a lot of sense to me.

I think this requires a change in the `Update` function to match.
ie. this:
https://github.com/matrix-org/pinecone/blob/e692df1a5c427cd554a49c43a4c2a90f311041c4/router/tree.go#L337

Maybe should be changed to:
``` go
	case newUpdate.Sequence <= lastGlobalUpdate.Sequence:
```
Currently the `Update` will change the parent selection if additional root announcements (with the same sequence) come in with shorter hop distances. Which would override the selected parent who received the latest root announcement first.

I'm not sure what the best logic would be here though.
If you always select a new parent if you receive a new sequence update from them faster than the other peers then you might end up flip-flopping between parents depending on how close their root latencies are.
So it might be best to keep it as is (checking both sequence and hop distance improvements), with the change to <= for the sequence number.

Then the parent would only be updated if a new sequence update was received by them faster **and** they have a shorter hop distance. That should prevent any flip-flopping and still align with the `selectNewParent` logic.
